### ISSUE TITLE
HTTP responses aren't closed and left open

### ISSUE THREAD

**Issue by samos123** [substratusai/lingo#22]
This causes the HTTP request to hang and never fully close

Steps to reproduce:
```
skaffold run
helm upgrade --install stapi-minilm-l6-v2 substratusai/stapi -f - << EOF
model: all-MiniLM-L6-v2
replicaCount: 0
deploymentAnnotations:
  lingo.substratus.ai/models: text-embedding-ada-002
EOF
curl -v http://localhost:8080/v1/embeddings \
  -H "Content-Type: application/json" \
  -d '{
    "input": "Your text string goes here",
    "model": "text-embedding-ada-002"
  }'
```

relevant logs:
```
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
2023/11/12 04:28:06 Admitted into queue
2023/11/12 04:28:06 Waiting for IPs
2023/11/12 04:28:06 Scaling model "stapi-minilm-l6-v2": 1
Dequeued:  2cb28540-19a1-4b1e-aa9f-a6fdf14eac6c
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
Dequeued:  2476f903-12fd-4d76-9cda-c128628ca43a
2023/11/12 04:28:06 Admitted into queue
2023/11/12 04:28:06 Waiting for IPs
2023/11/12 04:28:06 request: /v1/embeddings
2023/11/12 04:28:06 model: text-embedding-ada-002
2023/11/12 04:28:06 AtLeastOne()
2023/11/12 04:28:06 Entering queue
```

This seems to be introduced by #19

**Comment by samos123** [comment]
Seems the issue is that it dequeues right away before an IP is ready to serve:
```
2023/11/12 05:38:32 model: text-embedding-ada-002                                                               
2023/11/12 05:38:32 AtLeastOne()                                                                                
2023/11/12 05:38:32 Entering queue                                                                              
2023/11/12 05:38:32 Scaling model "stapi-minilm-l6-v2": 1                                                       
2023/11/12 05:38:32 Admitted into queue                                                                         
Dequeued:  92220202-2838-494d-9eae-7469c530e79c                                                                 
2023/11/12 05:38:32 Waiting for IPs                                                                             
2023/11/12 05:38:33 request: /v1/embeddings                                                                     
2023/11/12 05:38:33 model: text-embedding-ada-002                                                               
2023/11/12 05:38:33 AtLeastOne()
2023/11/12 05:38:33 Entering queue
2023/11/12 05:38:33 Admitted into queue
2023/11/12 05:38:33 Waiting for IPs
Dequeued:  e9a391a8-9f67-480e-838b-30e7e850676f
2023/11/12 05:38:33 request: /v1/embeddings
2023/11/12 05:38:33 model: text-embedding-ada-002
2023/11/12 05:38:33 AtLeastOne()
```

**Comment by samos123** [comment]
more relevant logs:
```
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: 7f85d05b-7511-4dff-adde-1c0a10e70aef                         
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: 26310c1d-3f61-4719-8813-60e7677a83e8                         
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: 03223c6e-f994-4fe4-9dd6-21ff920f5505                         
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: 24fdbeef-c2d3-4945-9c2c-68b725d043e6                         
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: 3c680504-3ed0-4cfd-9347-ce5b28fa2b9b                         
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: d4b425c9-1690-4a58-86d8-e91647a7ed32
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 Admitted into queue f26232a9-ec16-4b9e-8699-1da54ee9dd38
2023/11/12 06:39:50 Waiting for IPs f26232a9-ec16-4b9e-8699-1da54ee9dd38
2023/11/12 06:39:50 Got host: 10.244.0.7:8080, id: f26232a9-ec16-4b9e-8699-1da54ee9dd38
Dequeued:  f26232a9-ec16-4b9e-8699-1da54ee9dd38
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
2023/11/12 06:39:50 http: proxy error: context canceled
```

**Comment by nstogner** [comment]
I read this as the client cancelled the request by the time it reached the proxy portion of the handler. The queue happens before the IP is retrieved (which is a waiting operation for a ready Pod).

**Comment by nstogner** [comment]
Will attempt to reproduce on my side

**Comment by nstogner** [comment]
Ahh, yes the issue was introduced by #19 ...

The wait count that is returned by the queue and used by the autoscaler (post-scale-from-zero) only accounts for requests that are waiting in the queue. Previously, it reported `inQueue + inFlight`. So scale from zero is triggered by the request, then the autoscaler sees 0 requests in-queue and the autoscaler scales back down to 0 before the Pod ever becomes Ready. (upon dequeue but before completion the request is considered in-flight by the queue which reports to the autoscaler)

```bash
kubectl get pods -w
```

```
NAME                                READY   STATUS    RESTARTS   AGE
proxy-controller-57b656969b-gx82f   1/1     Running   0          21s
stapi-minilm-l6-v2-5dd7bb4fc8-gxfmq   0/1     Pending   0          0s
stapi-minilm-l6-v2-5dd7bb4fc8-gxfmq   0/1     Pending   0          0s
stapi-minilm-l6-v2-5dd7bb4fc8-gxfmq   0/1     ContainerCreating   0          0s
stapi-minilm-l6-v2-5dd7bb4fc8-gxfmq   0/1     Terminating         0          31s
```

**Comment by nstogner** [comment]
I will submit a fix soon.

**Comment by nstogner** [comment]
#21 fixes this

```
NAME                                  READY   STATUS    RESTARTS   AGE
proxy-controller-6b7f4f5c46-j88xk     1/1     Running   0          65s
stapi-minilm-l6-v2-5dd7bb4fc8-mk7s9   0/1     Running   0          4s
stapi-minilm-l6-v2-5dd7bb4fc8-mk7s9   1/1     Running   0          20s
stapi-minilm-l6-v2-5dd7bb4fc8-mk7s9   1/1     Terminating   0          81s
```

**Comment by samos123** [comment]
Turns out the completeFunc is locking up. I added logging statements inside the completeFunc function  noticed that it's getting stuck on this line:
```
q.listMtx.Lock()
```

I also saw the following logs:
```
2023/11/13 04:06:00 Running completeFunc:  2663354c-c276-4fab-a85a-36554f1c1314                                 
2023/11/13 04:06:00 Locking queue.list:  2663354c-c276-4fab-a85a-36554f1c1314                                   
2023/11/13 04:06:00 Item 2663354c-c276-4fab-a85a-36554f1c1314 inProgress: false                                 
2023/11/13 04:06:00 Finished completeFunc:  2663354c-c276-4fab-a85a-36554f1c1314                                
2023/11/13 04:06:00 http: panic serving 10.244.0.1:30684: runtime error: invalid memory address or nil pointer d
ereference                                                                                                      
goroutine 873 [running]:                                                                                        
net/http.(*conn).serve.func1()                                                                                  
        /usr/local/go/src/net/http/server.go:1868 +0xb9                                                         
panic({0x1608300?, 0x25f9ba0?})                                                                                 
        /usr/local/go/src/runtime/panic.go:920 +0x270                                                           
net/http/httputil.(*ReverseProxy).ServeHTTP(0xc0005c5ae0, {0x1a4e2e0, 0xc00054d7a0}, 0xc000812500)
        /usr/local/go/src/net/http/httputil/reverseproxy.go:480 +0xeb1                                          
main.(*Handler).ServeHTTP(0xc000127818, {0x1a4e2e0, 0xc00054d7a0}, 0xc000812400)
        /app/handler.go:63 +0xb25                                                                               
net/http.serverHandler.ServeHTTP({0x1a47fe0?}, {0x1a4e2e0?, 0xc00054d7a0?}, 0x6?)
        /usr/local/go/src/net/http/server.go:2938 +0x8e                                                         
net/http.(*conn).serve(0xc0006da2d0, {0x1a5a9d0, 0xc0003202d0})
        /usr/local/go/src/net/http/server.go:2009 +0x5f4                                                        
created by net/http.(*Server).Serve in goroutine 1                                                              
        /usr/local/go/src/net/http/server.go:3086 +0x5cb  
```
